[workspace]
channels = ["conda-forge"]
name = "numpy-wheel-build"
platforms = ["linux-64"]

[tasks]
build = "unset CFLAGS CXXFLAGS; python -m build -w"

[dependencies]
c-compiler = "*"
cxx-compiler = "*"
fortran-compiler = "*"
pkg-config = "*"
pip = "*"
python = "*"

[pypi-dependencies]
build = { git = "https://github.com/mgorny/build", branch = "variant-deps" }

[feature.mkl.dependencies]
mkl-devel = "*"

[feature.openblas.dependencies]
openblas = "*"

[environments]
mkl = ["mkl"]
openblas = ["openblas"]
