[workspace]
channels = ["conda-forge"]
name = "numpy-wheel-build"
platforms = ["linux-64"]

[tasks]
build = "bash build-variants.sh"

[dependencies]
auditwheel = "*"
c-compiler = "*"
cxx-compiler = "*"
fortran-compiler = "*"
pkg-config = "*"
pip = "*"
python = "3.13.*"
python-build = "*"
libxcrypt = "*"

[feature.mkl.dependencies]
mkl-devel = "*"

[environments]
mkl = ["mkl"]
openblas = []
