[workspace]
channels = ["conda-forge"]
name = "numpy-wheel-build"
platforms = ["linux-64"]

[tasks]
build = "python -m build -w"

[dependencies]
c-compiler = "*"
cxx-compiler = "*"
fortran-compiler = "*"
python-build = "*"
pkg-config = "*"

[feature.mkl.dependencies]
mkl-devel = "*"

[feature.openblas.dependencies]
openblas = "*"

[environments]
mkl = ["mkl"]
openblas = ["openblas"]
