# Workflow to build and test wheels.
# To work on the wheel building infrastructure on a fork, comment out:
#
# if: github.repository == 'numpy/numpy'
#
# in the get_commit_message job. Be sure to include [wheel build] in your commit
# message to trigger the build. All files related to wheel building are located
# at tools/wheels/
# Alternatively, you can add labels to the pull request in order to trigger wheel
# builds.
# The labels that trigger builds are:
# 36 - Build(for changes to the building process,
# 14 - Release(ensure wheels build before release)
name: Wheel builder

on:
  push:

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build_wheels_x86_64:
    name: Build wheel ${{ matrix.python }}-${{ matrix.blas }}-x86_64-${{ matrix.x86_64 }}-${{ matrix.plat }}
    runs-on: ${{ matrix.plat }}
    strategy:
      # Ensure that a wheel builder finishes even if another fails
      fail-fast: false
      matrix:
        blas: []
        python: ["3.10", "3.11", "3.12", "3.13"]
        x86_64: [v1, v2, v3, v4]
        plat: [ubuntu-22.04, macos-13]

    steps:
      - name: Checkout numpy
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: true
          persist-credentials: false

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Build variant wheel
        if: matrix.x86_64 != ''
        env:
          PLAT: linux_x86_64
        run: bash build-variants.sh -Csetup-args=-Duse-ilp64=true -Cvariant=x86_64::level::${{ matrix.x86_64 }} -Ccompile-args=-v

      - name: Build non-variant wheel
        if: matrix.x86_64 == ''
        env:
          PLAT: linux_x86_64
        run: bash build-variants.sh -Csetup-args=-Duse-ilp64=true -Ccompile-args=-v

      - uses: actions/upload-artifact@v4
        with:
          name: wheel-${{ matrix.blas }}-${{ matrix.python }}-x86-64-${{ matrix.x86_64 }}-${{ matrix.plat }}
          path: wheelhouse/*.whl
          if-no-files-found: error
          compression-level: 0

  build_wheels_aarch64:
    name: Build wheel ${{ matrix.python }}-${{ matrix.blas }}-armv-${{ matrix.aarch64 }}-${{ matrix.plat }}
    runs-on: ${{ matrix.plat }}
    strategy:
      matrix:
        blas: []
        python: ["3.10", "3.11", "3.12", "3.13"]
        aarch64: ["8a", "8.1a", "8.2a", "8.3a", "8.4a", "8.5a", "9.0a"]
        plat: [ubuntu-22.04-arm, macos-14]

    steps:
      - name: Checkout numpy
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: true
          persist-credentials: false

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Build variant wheel
        if: matrix.aarch64 != ''
        env:
          PLAT: linux_aarch64
        run: bash build-variants.sh -Csetup-args=-Duse-ilp64=true -Cvariant=aarch64::version::${{ matrix.aarch64 }} -Ccompile-args=-v

      - name: Build non-variant wheel
        if: matrix.aarch64 == ''
        env:
          PLAT: linux_aarch64
        run: bash build-variants.sh -Csetup-args=-Duse-ilp64=true -Ccompile-args=-v

      - uses: actions/upload-artifact@v4
        with:
          name: wheel-${{ matrix.blas }}-${{ matrix.python }}-aarch64-armv${{ matrix.aarch64 }}-${{ matrix.plat }}
          path: wheelhouse/*.whl
          if-no-files-found: error
          compression-level: 0

  combine_artifacts:
    name: Combine artifacts
    runs-on: ubuntu-22.04
    needs: [build_wheels_x86_64, build_wheels_aarch64]
    steps:
      - uses: actions/download-artifact@v4
      - uses: actions/upload-artifact@v4
        with:
          name: combined
          path: "*/*.whl"
          if-no-files-found: error
          compression-level: 0
